# 这是 wrangler 的配置文件，也就是给部署机器人的说明书，喵~

# 这里的名字最好和主人你在 Cloudflare 上创建的项目名保持一致
name = "doh" 

# 告诉 wrangler 你的主要代码是哪个文件，这是最关键的一步！
main = "index.js" 

# 这是一个兼容性日期，保证你的代码能正常运行，照着写就好啦
compatibility_date = "2025-11-06"
